version: "3"

services:

  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - SW_CURRENCY=EUR


networks:
  web:
    external: false
