version: "3"

services:
  shopware:
    image: dockware/dev:5.7.2
    container_name: shopware5
    ports:
      - "8080:80"
      - "2222:22"
      - "8888:8888"
      - "9999:9999"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=7.4

networks:
  web:
    external: false
